import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Header/navbar";
import Footer from "@/components/Footer/footer";
import NavSecond from "@/components/Header/navSecondary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FBR Automotive",
  description: "Generated by WEAREITDZ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className }>
      <div className=" ">
        <NavSecond />
        </div> 
                {children}
        <Footer />
         </body>
    </html>
  );
}
